In [1]:
# import req. lib.

import numpy as np
import pandas as pd

In [2]:
# Read the dataset

df = pd.read_csv('/content/Google_Stock_Price_Train.csv')
df.head()

Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

In [3]:
df.tail()

Date    Open    High     Low   Close     Volume
1253  12/23/2016  790.90  792.74  787.28  789.91    623,400
1254  12/27/2016  790.68  797.86  787.66  791.55    789,100
1255  12/28/2016  793.70  794.23  783.20  785.05  1,153,800
1256  12/29/2016  783.33  785.93  778.92  782.79    744,300
1257  12/30/2016  782.75  782.78  770.41  771.82  1,770,000

In [4]:
# Checking datatype

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    1258 non-null   object 
 1   Open    1258 non-null   float64
 2   High    1258 non-null   float64
 3   Low     1258 non-null   float64
 4   Close   1258 non-null   object 
 5   Volume  1258 non-null   object 
dtypes: float64(3), object(3)
memory usage: 59.1+ KB


In [6]:
# Taking important column

train_set = df.iloc[:,1:2].values
train_set

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

In [7]:
# Scaling values

from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler()
scaled_tr = sc.fit_transform(train_set)
scaled_tr

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

In [9]:
sc.inverse_transform([[0.93796041]])

array([[783.329998]])

In [ ]:
"""
Input: 1  2  3  4  5  6  7  8  9  10      t=3

    x         y
  1 2 3       4
  2 3 4       5
  3 4 5       6
  4 5 6       7
  5 6 7       8
  6 7 8       9
  7 8 9       10
  8 9 10      11
 


"""

In [11]:
scaled_tr[60-60:60,0]

array([0.08581368, 0.09701243, 0.09433366, 0.09156187, 0.07984225,
       0.0643277 , 0.0585423 , 0.06568569, 0.06109085, 0.06639259,
       0.0614257 , 0.07474514, 0.02797827, 0.02379269, 0.02409033,
       0.0159238 , 0.01078949, 0.00967334, 0.01642607, 0.02100231,
       0.02280676, 0.02273235, 0.02810849, 0.03212665, 0.0433812 ,
       0.04475779, 0.04790163, 0.0440695 , 0.04648783, 0.04745517,
       0.04873875, 0.03936305, 0.04137213, 0.04034898, 0.04784582,
       0.04325099, 0.04356723, 0.04286033, 0.04602277, 0.05398467,
       0.05738894, 0.05714711, 0.05569611, 0.04421832, 0.04514845,
       0.04605997, 0.04412531, 0.03675869, 0.04486941, 0.05065481,
       0.05214302, 0.05612397, 0.05818885, 0.06540665, 0.06882953,
       0.07243843, 0.07993526, 0.07846566, 0.08034452, 0.08497656])

In [12]:
# Spliting into dependent and independent

x_train = []
y_train = []

for i in range(60,1258):
  x_train.append(scaled_tr[i-60:i,0])
  y_train.append(scaled_tr[i,0])

In [13]:
x_train

[array([0.08581368, 0.09701243, 0.09433366, 0.09156187, 0.07984225,
        0.0643277 , 0.0585423 , 0.06568569, 0.06109085, 0.06639259,
        0.0614257 , 0.07474514, 0.02797827, 0.02379269, 0.02409033,
        0.0159238 , 0.01078949, 0.00967334, 0.01642607, 0.02100231,
        0.02280676, 0.02273235, 0.02810849, 0.03212665, 0.0433812 ,
        0.04475779, 0.04790163, 0.0440695 , 0.04648783, 0.04745517,
        0.04873875, 0.03936305, 0.04137213, 0.04034898, 0.04784582,
        0.04325099, 0.04356723, 0.04286033, 0.04602277, 0.05398467,
        0.05738894, 0.05714711, 0.05569611, 0.04421832, 0.04514845,
        0.04605997, 0.04412531, 0.03675869, 0.04486941, 0.05065481,
        0.05214302, 0.05612397, 0.05818885, 0.06540665, 0.06882953,
        0.07243843, 0.07993526, 0.07846566, 0.08034452, 0.08497656]),
 array([0.09701243, 0.09433366, 0.09156187, 0.07984225, 0.0643277 ,
        0.0585423 , 0.06568569, 0.06109085, 0.06639259, 0.0614257 ,
        0.07474514, 0.02797827, 0.02379269, 0.

In [14]:
# Convert list into array

x_train,y_train = np.array(x_train),np.array(y_train)

In [15]:
x_train.shape

(1198, 60)

In [16]:
# (1198, 60, 1)

# Convert shape

x_train = np.reshape(x_train,(1198, 60, 1))
x_train.shape

(1198, 60, 1)

In [17]:
# Building model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [18]:
model = Sequential()
model.add(LSTM(50, input_shape=(60, 1),return_sequences=True))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50,return_sequences=True))
model.add(Dense(1))

In [19]:
model.compile(optimizer='adam',loss='mse')

In [20]:
model.fit(x_train,y_train,batch_size=32,epochs=5)

Epoch 1/5
38/38 [==============================] - 12s 114ms/step - loss: 0.1199
Epoch 2/5
38/38 [==============================] - 4s 115ms/step - loss: 0.0865
Epoch 3/5
38/38 [==============================] - 5s 129ms/step - loss: 0.0816
Epoch 4/5
38/38 [==============================] - 4s 113ms/step - loss: 0.0799
Epoch 5/5
38/38 [==============================] - 4s 111ms/step - loss: 0.0789


In [21]:
# save model

model.save('LSTM.h5')